---
- hosts: all
  become: true
  gather_facts: true

  vars:
    docker_needed: "{{ (docker_cli.rc != 0) or (compose.cli.rc != 0) }}"

  tasks:
    - name: Check for Docker CLI
      command: docker --version
      register: docker_cli
      changed_when: false
      ignore_errors: true

    - name: Check for Docker Compose plugin
      command: docker compose version
      register: compose_cli
      changed_when: false
      ignore_errors: true

    - name: Install prerequisites for Docker (APT hosts only)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when:
        - ansible_os_family == "Debian"
        - docker_needed

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when:
        - ansible_os_family == "Debian"
        - docker_needed

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
        update_cache: yes
      when:
        - ansible_os_family == "Debian"
        - docker_needed

    - name: Install Docker Engine + Compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes
      when:
        - ansible_os_family == "Debian"
        - docker_needed

    - name: Report installation result
      debug:
        msg: >-
          {% if docker_needed %}
            ✅ Installed Docker and Compose plugin on {{ inventory_hostname }}
          {% else %}
            ✅ Docker ({{ docker_cli.stdout }}) and Compose ({{ compose_cli.stdout }}) already present on {{ inventory_hostname }}
          {% endif %}
