---
- name: Pull & deploy latest Docker Compose stacks
  hosts: all
  become: true
  vars:
    compose_search_paths:
      - /opt
      - /srv
      - /home
  tasks:

    - name: Discover all docker-compose.yml files
      find:
        paths: "{{ compose_search_paths }}"
        patterns: "docker-compose.yml"
      register: compose_manifests

    - name: Pull latest images & bring up the stack
      community.docker.docker_compose_v2:
        project_src: "{{ item.path | dirname }}"
        pull: yes
        state: present
      loop: "{{ compose_manifests.files }}"
      loop_control:
        label: "{{ item.path }}"
